### ISSUE TITLE
Get goldfinch playbook working with: custom.yml

### ISSUE THREAD

**Issue by agstephens** [cedadev/ceda-wps-migration#16]
Example `custom.yml`:

```
---
demo: false
# On vagrant, might need to do:
# yum install:
#     http://yumit.jc.rl.ac.uk/yum/jasmin/7/RPMS/jasmin-repo-1.2-2.el7.noarch.rpm
#     epel-release,yum-priorities
#data_dir: /vagrant/.local/data
# rm /etc/yum.repos.d/epel.repo to re-run when changed
epel_repo_disable: true
db_install_postgresql: true
db_install_sqlite: false
db_host: "192.168.50.80"
postgresql_pg_hba_md5_hosts: ['192.168.50.80/32']
slurm_enabled: false
service_user: wps
service_add_user: true
#wps_basedir: /gws/smf/j04/cp4cds1/c3s_34e/rook_prod
wps_services:
  - name: goldfinch
    repo: https://github.com/cedadev/goldfinch.git
    version: main
    hostname: "192.168.50.80"
    port: 80
    mode: scheduler
    maxprocesses: 10000
    parallelprocesses: 1000
    cleantempdir: false
```

Some fixes to be added on the server:

```
curl "http://192.168.50.80/wps?service=WPS&version=1.0.0&request=GetCapabilities"

mkdir -p /badc/ukmo-midas/data /badc/ukmo-midas/metadata

systemctl restart nginx
systemctl restart postgresql-11.service
systemctl restart supervisord.service
supervisorctl restart goldfinch

tail -f /var/log/nginx/error.log
tail -f /var/log/pywps/goldfinch.log
```
