### ISSUE TITLE
How to serve multiple WPSs from the same server?

### ISSUE THREAD

**Issue by agstephens** [cedadev/ceda-wps-migration#21]
I think Carsten puts them on different ports.

But maybe we should have a convention of:

`http://<server>/<service_id>/wps`

Where `<service_id>` might be `midas_extract`.

Initial approach will just use different ports:
80, 9001, 9002 etc

**Comment by agstephens** [comment]
This can be done with the Ansible playbook - with some changes made. Here is an example (test) `custom.yml` file:

```
---
demo: false
# On vagrant, might need to do:
# yum install:
#     http://yumit.jc.rl.ac.uk/yum/jasmin/7/RPMS/jasmin-repo-1.2-2.el7.noarch.rpm
#     epel-release,yum-priorities
#data_dir: /vagrant/.local/data
# rm /etc/yum.repos.d/epel.repo to re-run when changed
epel_repo_disable: true
db_install_postgresql: true
db_install_sqlite: false
db_host: "999.16.149.197"
postgresql_pg_hba_md5_hosts: ['999.16.149.197/32']
slurm_enabled: true
service_user: cwps
service_add_user: false
wps_basedir: /gws/nopw/j04/ceda_wps/birds/test
wps_services:
  - name: flamingo
    repo: https://github.com/cedadev/flamingo.git
    flamingo_enabled: true
    flamingo_site: "demo"
    version: main
    hostname: "ceda-wps-stag.ceda.ac.uk"
    port: 9001
    mode: scheduler
    maxprocesses: 10000
    parallelprocesses: 1000
    cleantempdir: false
    environment:
      OMP_NUM_THREADS: 1
      MKL_NUM_THREADS: 1
      OPENBLAS_NUM_THREADS: 1
  - name: goldfinch
    repo: https://github.com/cedadev/goldfinch.git
    version: main
    hostname: "ceda-wps-stag.ceda.ac.uk"
    port: 9002
    mode: scheduler
    maxprocesses: 10000
    parallelprocesses: 1000
    cleantempdir: false
  - name: vulture
    repo: https://github.com/cedadev/vulture.git
    version: main
    hostname: "ceda-wps-stag.ceda.ac.uk"
    port: 9003
    mode: default
    maxprocesses: 10000
    parallelprocesses: 1000
    cleantempdir: false

```
